### ISSUE TITLE
Need example for SCHSIM old I/O

### ISSUE THREAD

**Issue by uturuncoglu** [ec-jrc/Thalassa#62]
Is there any example to read SCHSIM old I/O files? I could not find examples of reading multiple files like following,

```
../schout_000000_1.nc
../schout_000000_2.nc
../schout_000001_1.nc
../schout_000001_2.nc
../schout_000002_1.nc
../schout_000002_2.nc
../schout_000003_1.nc
../schout_000003_2.nc
```

I tried to open single file such as `schout_000001_1.nc` but then the tool complain about the `lon` variable. Maybe I need to read mesh first but not sure since the examples are for ADCIRC at this point.

**Comment by brey** [comment]
Hi @uturuncoglu. Thanks for the interest. In order to visualise the data in Thalassa, you need to merge the data into complete datasets. This can be done either with the fortran function available from the SCHISM community  or using [pyposeidon](https://pyposeidon.readthedocs.io/en/latest/model.html). 

Once the combined datasets are done you can try to load it again into Thalassa. 

If you model is global, there is the need of an additional pre-processing step that deals with the International time line in order to avoid the 3d artefacts of the mesh. If that is the case, let me know and I can provide more info. 

Let me know who it goes.

**Comment by pmav99** [comment]
@uturuncoglu You can download a sample netcdf that can be visualized by thalassa from here: https://static.techrad.eu/thalassa/2022090100.nc

For the global meshes and the International Date Line, please have a look here: https://github.com/ec-jrc/Thalassa/issues/58

**Comment by pmav99** [comment]
> using [pyposeidon](https://pyposeidon.readthedocs.io/en/latest/model.html).

@uturuncoglu If you want to give a try to pyposeidon, you can set it up to use an existing schism model like this:

``` python
import pyposeidon

# Create a model instance
model = pyposeidon.model.set(
    solver_name="schism",
    rpath="/path/to/directory/",  # UPDATE this path to the directory that contains `param.nml`. Make sure to add the trailing slash!
)

# Call the `.results()` method. This will merge the data, take care of the global to local conversion etc.
model.results()
```

So if your `output` directory contains:
```
../schout_000000_1.nc
../schout_000000_2.nc
../schout_000001_1.nc
../schout_000001_2.nc
../schout_000002_1.nc
../schout_000002_2.nc
../schout_000003_1.nc
../schout_000003_2.nc
```

After running the above snippet, 2 more files will be created:
```
../schout_1.nc
../schout_2.nc
```
These files will be visualizable by thalassa. 

Disclaimer: we have only tested pyposeidon on schism 5.9 and 5.10 + NEW IO. schism 5.10 + OLD IO has not been tested, but in theory it should work. If you do try it please let us know how it goes. if you run into trouble, we should be able to sort it out, too.

**Comment by uturuncoglu** [comment]
@brey @pmav99 Thanks both of you for your help and the detailed information. At this point, I am able to combine files with `autocombine_MPI_elfe.pl` and create some simple visualizations under VisIT but it is not powerful and time consuming. Anyway, I'll try to use `pyposeidon` to merge files and try to create visualization with Thalassa. I have already install it under my Conda environment (using pip) but I was getting error like `AttributeError: module 'thalassa' has no attribute 'open_dataset'`. It seems that the installation is fine but I'll try again. In the mean time if you have any suggestion about installation under Conda, just let me know.

**Comment by pmav99** [comment]
@uturuncoglu creating a new thalassa release and creating packages is one of the things that I am working on these days. In the meantime I suggest that you install thalassa like this:
``` bash
# 0. Install geos. Use can use `apt`, `conda` or whatever you prefer. If you don't have it, then step 4. will fail.
# 1. Create a new python environment using conda, venv, or whatever you use. Activate it, too
# 2. Make sure that pip is up to date
python -mpip install -U pip 
# 3. Clone the repo and cd into it
git clone https://github.com/ec-jrc/Thalassa.git thalassa
cd thalassa
# 4. Install thalassa. 
python -mpip install -r requirements/requirements.txt  
# 5. Test the installation
python -c 'import thalassa' && echo 'OK!' 
# 6. Download some sample data
mkdir -p data
wget -O data/2022090100.nc  https://static.techrad.eu/thalassa/2022090100.nc
# 7. Run thalassa
python -mpanel serve run.py
```

After that, visit `http://localhost:5006` and you see the thalassa UI

Give it a try and let me know how it goes.

**Comment by uturuncoglu** [comment]
@pmav99 I am not sure it is an installation issue or not but I am getting following error from `pyposeidon.model.set` command. I'll try with my local machine to see what happens.

```
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
Cell In[15], line 2
      1 # create a model instance
----> 2 model = pyposeidon.model.set(solver_name="schism", rpath="/glade/scratch/turuncu/COASTAL_APP/ike_shinnecock.atm2sch")

AttributeError: 'function' object has no attribute 'set'
```

**Comment by brey** [comment]
@uturuncoglu It could be that you are using an older version of `pyposeidon`. Note that due to an upstream dependency issue we never released v0.6 on pip (we'll remedy that asap). Could you please try with `conda` or `mamba`

```
conda install -c conda-forge pyposeidon 
```
or
```
mamba install -c conda-forge pyposeidon 
```

and make sure you have version 0.6.

**Comment by uturuncoglu** [comment]
@brey Thanks for your help. The default version was `0.5.2` and working with `3.11.*`. When I tried to install `0.6`, it forced me to use Python < 3.9. So, I created conda environment with Python `3.8.10`. Here are my commands to create a working environment,

```
conda create --name schism python=3.8.10
conda activate schism
conda install -c conda-forge mamba
mamba install -c conda-forge pyposeidon=0.6

optional to use notebook along with conda environment:
mamba install -c conda-forge notebook jupyterlab jupyter_contrib_nbextensions nb_conda_kernels
```

Then, I run the command that you provided to combine the files, it gives following error,

```
INFO:pyposeidon.schism:retrieving index references ... 

---------------------------------------------------------------------------
IndexError                                Traceback (most recent call last)
Cell In[3], line 1
----> 1 model.results()

File ~/miniconda3/envs/schism/lib/python3.8/site-packages/pyposeidon/schism.py:1317, in Schism.results(self, **kwargs)
   1315 if len(self.misc) == 0:
   1316     logger.info("retrieving index references ... \n")
-> 1317     self.global2local(**kwargs)
   1318     logger.info("... done \n")
   1320 # Create mesh xarray Dataset

File ~/miniconda3/envs/schism/lib/python3.8/site-packages/pyposeidon/schism.py:855, in Schism.global2local(self, **kwargs)
    850     keys.append("core{}".format(name.split("/")[-1].split("_")[-1]))
    852 # Parsing the files
    853 
    854 # We read from the first file the header (it is the same for all)
--> 855 with open(gfiles[0], "r") as f:
    856     header = pd.read_csv(
    857         f,
    858         header=None,
   (...)
    880         ],
    881     )
    883 # get the number of elems from all files

IndexError: list index out of range
```

It seems that `gfiles` is empty list in my case. I check the code (`pyposeidon/schism.py`) and I think the `rpath` needs to have '/' at the end. It would be better to change `gfiles = glob.glob(path + "outputs/local_to_global_*")` to `gfiles = glob.glob(os.path.join(path, "outputs/local_to_global_*"))` but not sure. I did not test it. Anyway, once I solve the `gfiles` issue. I run the script again but then it gave me following error,

```
INFO:pyposeidon.schism:... done 

INFO:pyposeidon.schism:done with node based variables 

INFO:pyposeidon.schism:done with side based variables 

Traceback (most recent call last):
  File "merge.py", line 12, in <module>
    model.results()
  File "/Users/turuncu/miniconda3/envs/schism/lib/python3.8/site-packages/pyposeidon/schism.py", line 1476, in results
    sdate = pd.Timestamp(
  File "pandas/_libs/tslibs/timestamps.pyx", line 1656, in pandas._libs.tslibs.timestamps.Timestamp.__new__
  File "pandas/_libs/tslibs/timezones.pyx", line 172, in pandas._libs.tslibs.timezones.maybe_get_tz
TypeError: unsupported type for timedelta seconds component: numpy.int64
```

Any suggestion?

**Comment by pmav99** [comment]
Yes, `rpath` needs to be a directory and it seems that you must ensure that it ends in a slash. 

Since this is a pandas error, and pandas 2.0 was released last week, can you check which pandas version you are using? Is it 1.5.X or 2.X? If it is 2.X then it seems that there is some sort of incompatibility, so I would suggest that you downgrade to 1.5.X

PS. ideally the discussion about pyposeidon should happen in the pyposeidon repo. No big deal though.

**Comment by uturuncoglu** [comment]
@pmav99 Okay. Thanks for your help. `mamba install -c conda-forge pandas==1.5.3` solved the issue. I also installed Thalassa to another environment and it seems it is working. I am only seeing couple of variables pressure, elevation etc. but not wind speed data. Is it expected?

**Comment by pmav99** [comment]
>  I am only seeing couple of variables pressure, elevation etc. but not wind speed data. Is it expected?

Can you post the output of `ncdump -sh /path/to/file.nc` for the netcdf file you are using?

For the record, thalassa knows how to visualize data variables whose dimensions are either:

- `node`
- `time, node`
- `time, node, layer`  (this is for 3D meshes)

https://github.com/ec-jrc/Thalassa/blob/5677aee21ca187557d9d97add8fa186b59b22d25/thalassa/utils.py#L24-L37

**Comment by uturuncoglu** [comment]
@pmav99 Here is the output from the command. As I see some variables have dimension like `two`. Maybe u, and v components of the wind for wind speed. Not sure.

```
netcdf schout_1 {
dimensions:
	time = 48 ;
	nSCHISM_hgrid_edge = 8849 ;
	nSCHISM_hgrid_face = 5780 ;
	nSCHISM_hgrid_node = 3070 ;
	two = 2 ;
	one = 1 ;
	sigma = 2 ;
	nMaxSCHISM_hgrid_face_nodes = 4 ;
variables:
	float wetdry_side(time, nSCHISM_hgrid_edge) ;
		wetdry_side:_FillValue = NaNf ;
		wetdry_side:_Storage = "contiguous" ;
		wetdry_side:_Endianness = "little" ;
	float wetdry_elem(time, nSCHISM_hgrid_face) ;
		wetdry_elem:_FillValue = NaNf ;
		wetdry_elem:_Storage = "contiguous" ;
		wetdry_elem:_Endianness = "little" ;
	float wetdry_node(time, nSCHISM_hgrid_node) ;
		wetdry_node:_FillValue = NaNf ;
		wetdry_node:_Storage = "contiguous" ;
		wetdry_node:_Endianness = "little" ;
	float elev(time, nSCHISM_hgrid_node) ;
		elev:_FillValue = NaNf ;
		elev:_Storage = "contiguous" ;
		elev:_Endianness = "little" ;
	float air_pressure(time, nSCHISM_hgrid_node) ;
		air_pressure:_FillValue = NaNf ;
		air_pressure:_Storage = "contiguous" ;
		air_pressure:_Endianness = "little" ;
	float wind_speed(time, nSCHISM_hgrid_node, two) ;
		wind_speed:_FillValue = NaNf ;
		wind_speed:_Storage = "contiguous" ;
		wind_speed:_Endianness = "little" ;
	float dahv(time, nSCHISM_hgrid_node, two) ;
		dahv:_FillValue = NaNf ;
		dahv:_Storage = "contiguous" ;
		dahv:_Endianness = "little" ;
	int64 time(time) ;
		time:long_name = "Time" ;
		time:base_date = "2008 8 23 0 0" ;
		time:standard_name = "time" ;
		time:units = "minutes since 2008-08-23 00:30:00" ;
		time:calendar = "proleptic_gregorian" ;
		time:_Storage = "contiguous" ;
		time:_Endianness = "little" ;
	int64 coordinate_system_flag(one) ;
		coordinate_system_flag:_Storage = "contiguous" ;
		coordinate_system_flag:_Endianness = "little" ;
	double minimum_depth(one) ;
		minimum_depth:_FillValue = NaN ;
		minimum_depth:_Storage = "contiguous" ;
		minimum_depth:_Endianness = "little" ;
	double sigma_h_c(one) ;
		sigma_h_c:_FillValue = NaN ;
		sigma_h_c:long_name = "ocean_s_coordinate h_c constant" ;
		sigma_h_c:units = "meters" ;
		sigma_h_c:positive = "down" ;
		sigma_h_c:_Storage = "contiguous" ;
		sigma_h_c:_Endianness = "little" ;
	double sigma_theta_b(one) ;
		sigma_theta_b:_FillValue = NaN ;
		sigma_theta_b:long_name = "ocean_s_coordinate theta_b constant" ;
		sigma_theta_b:_Storage = "contiguous" ;
		sigma_theta_b:_Endianness = "little" ;
	double sigma_theta_f(one) ;
		sigma_theta_f:_FillValue = NaN ;
		sigma_theta_f:long_name = "ocean_s_coordinate theta_f constant" ;
		sigma_theta_f:_Storage = "contiguous" ;
		sigma_theta_f:_Endianness = "little" ;
	double sigma_maxdepth(one) ;
		sigma_maxdepth:_FillValue = NaN ;
		sigma_maxdepth:long_name = "ocean_s_coordinate maximum depth cutoff (mixed s over z boundary)" ;
		sigma_maxdepth:units = "meters" ;
		sigma_maxdepth:positive = "down" ;
		sigma_maxdepth:_Storage = "contiguous" ;
		sigma_maxdepth:_Endianness = "little" ;
	double Cs(sigma) ;
		Cs:_FillValue = NaN ;
		Cs:long_name = "Function C(s) at whole levels" ;
		Cs:positive = "up" ;
		Cs:_Storage = "contiguous" ;
		Cs:_Endianness = "little" ;
	double sigma(sigma) ;
		sigma:_FillValue = NaN ;
		sigma:long_name = "S coordinates at whole levels" ;
		sigma:units = "1" ;
		sigma:standard_name = "ocean_s_coordinate" ;
		sigma:positive = "up" ;
		sigma:h_s = 1000000. ;
		sigma:h_c = 100. ;
		sigma:theta_b = 1. ;
		sigma:theta_f = 0.0001 ;
		sigma:formula_terms = "s: sigma eta: elev depth: depth a: sigma_theta_f b: sigma_theta_b depth_c: sigma_h_c" ;
		sigma:_Storage = "contiguous" ;
		sigma:_Endianness = "little" ;
	int64 dry_value_flag(one) ;
		dry_value_flag:values = "0: use last-wet value; 1: use junk" ;
		dry_value_flag:_Storage = "contiguous" ;
		dry_value_flag:_Endianness = "little" ;
	int64 SCHISM_hgrid(one) ;
		SCHISM_hgrid:long_name = "Topology data of 2d unstructured mesh" ;
		SCHISM_hgrid:topology_dimension = 2LL ;
		SCHISM_hgrid:cf_role = "mesh_topology" ;
		SCHISM_hgrid:node_coordinates = "SCHISM_hgrid_node_x SCHISM_hgrid_node_y" ;
		SCHISM_hgrid:face_node_connectivity = "SCHISM_hgrid_face_nodes" ;
		SCHISM_hgrid:edge_coordinates = "SCHISM_hgrid_edge_x SCHISM_hgrid_edge_y" ;
		SCHISM_hgrid:face_coordinates = "SCHISM_hgrid_face_x SCHISM_hgrid_face_y" ;
		SCHISM_hgrid:edge_node_connectivity = "SCHISM_hgrid_edge_nodes" ;
		SCHISM_hgrid:_Storage = "contiguous" ;
		SCHISM_hgrid:_Endianness = "little" ;
	double SCHISM_hgrid_node_x(nSCHISM_hgrid_node) ;
		SCHISM_hgrid_node_x:_FillValue = NaN ;
		SCHISM_hgrid_node_x:long_name = "node x-coordinate" ;
		SCHISM_hgrid_node_x:standard_name = "longitude" ;
		SCHISM_hgrid_node_x:units = "degrees_east" ;
		SCHISM_hgrid_node_x:mesh = "SCHISM_hgrid" ;
		SCHISM_hgrid_node_x:_Storage = "contiguous" ;
		SCHISM_hgrid_node_x:_Endianness = "little" ;
	double SCHISM_hgrid_node_y(nSCHISM_hgrid_node) ;
		SCHISM_hgrid_node_y:_FillValue = NaN ;
		SCHISM_hgrid_node_y:long_name = "node y-coordinate" ;
		SCHISM_hgrid_node_y:standard_name = "latitude" ;
		SCHISM_hgrid_node_y:units = "degrees_north" ;
		SCHISM_hgrid_node_y:mesh = "SCHISM_hgrid" ;
		SCHISM_hgrid_node_y:_Storage = "contiguous" ;
		SCHISM_hgrid_node_y:_Endianness = "little" ;
	double depth(nSCHISM_hgrid_node) ;
		depth:_FillValue = NaN ;
		depth:long_name = "Bathymetry" ;
		depth:units = "meters" ;
		depth:positive = "down" ;
		depth:mesh = "SCHISM_hgrid" ;
		depth:location = "node" ;
		depth:_Storage = "contiguous" ;
		depth:_Endianness = "little" ;
	int64 node_bottom_index(nSCHISM_hgrid_node) ;
		node_bottom_index:long_name = "bottom level index at each node" ;
		node_bottom_index:units = "non-dimensional" ;
		node_bottom_index:mesh = "SCHISM_hgrid" ;
		node_bottom_index:location = "node" ;
		node_bottom_index:start_index = 0LL ;
		node_bottom_index:_Storage = "contiguous" ;
		node_bottom_index:_Endianness = "little" ;
	double SCHISM_hgrid_face_nodes(nSCHISM_hgrid_face, nMaxSCHISM_hgrid_face_nodes) ;
		SCHISM_hgrid_face_nodes:_FillValue = NaN ;
		SCHISM_hgrid_face_nodes:long_name = "Horizontal Element Table" ;
		SCHISM_hgrid_face_nodes:cf_role = "face_node_connectivity" ;
		SCHISM_hgrid_face_nodes:start_index = 0LL ;
		SCHISM_hgrid_face_nodes:_Storage = "contiguous" ;
		SCHISM_hgrid_face_nodes:_Endianness = "little" ;
	double SCHISM_hgrid_face_x(nSCHISM_hgrid_face) ;
		SCHISM_hgrid_face_x:_FillValue = NaN ;
		SCHISM_hgrid_face_x:long_name = "x_coordinate of 2D mesh face" ;
		SCHISM_hgrid_face_x:standard_name = "longitude" ;
		SCHISM_hgrid_face_x:units = "degrees_east" ;
		SCHISM_hgrid_face_x:mesh = "SCHISM_hgrid" ;
		SCHISM_hgrid_face_x:_Storage = "contiguous" ;
		SCHISM_hgrid_face_x:_Endianness = "little" ;
	double SCHISM_hgrid_face_y(nSCHISM_hgrid_face) ;
		SCHISM_hgrid_face_y:_FillValue = NaN ;
		SCHISM_hgrid_face_y:long_name = "y_coordinate of 2D mesh face" ;
		SCHISM_hgrid_face_y:standard_name = "latitude" ;
		SCHISM_hgrid_face_y:units = "degrees_north" ;
		SCHISM_hgrid_face_y:mesh = "SCHISM_hgrid" ;
		SCHISM_hgrid_face_y:_Storage = "contiguous" ;
		SCHISM_hgrid_face_y:_Endianness = "little" ;
	int64 ele_bottom_index(nSCHISM_hgrid_face) ;
		ele_bottom_index:long_name = "bottom level index at each element" ;
		ele_bottom_index:units = "non-dimensional" ;
		ele_bottom_index:mesh = "SCHISM_hgrid" ;
		ele_bottom_index:location = "elem" ;
		ele_bottom_index:start_index = 0LL ;
		ele_bottom_index:_Storage = "contiguous" ;
		ele_bottom_index:_Endianness = "little" ;
	double SCHISM_hgrid_edge_nodes(nSCHISM_hgrid_edge, two) ;
		SCHISM_hgrid_edge_nodes:_FillValue = NaN ;
		SCHISM_hgrid_edge_nodes:long_name = "Map every edge to the two nodes that it connects" ;
		SCHISM_hgrid_edge_nodes:cf_role = "edge_node_connectivity" ;
		SCHISM_hgrid_edge_nodes:start_index = 0LL ;
		SCHISM_hgrid_edge_nodes:_Storage = "contiguous" ;
		SCHISM_hgrid_edge_nodes:_Endianness = "little" ;
	double SCHISM_hgrid_edge_x(nSCHISM_hgrid_edge) ;
		SCHISM_hgrid_edge_x:_FillValue = NaN ;
		SCHISM_hgrid_edge_x:long_name = "x_coordinate of 2D mesh edge" ;
		SCHISM_hgrid_edge_x:standard_name = "longitude" ;
		SCHISM_hgrid_edge_x:units = "degrees_east" ;
		SCHISM_hgrid_edge_x:mesh = "SCHISM_hgrid" ;
		SCHISM_hgrid_edge_x:_Storage = "contiguous" ;
		SCHISM_hgrid_edge_x:_Endianness = "little" ;
	double SCHISM_hgrid_edge_y(nSCHISM_hgrid_edge) ;
		SCHISM_hgrid_edge_y:_FillValue = NaN ;
		SCHISM_hgrid_edge_y:long_name = "y_coordinate of 2D mesh edge" ;
		SCHISM_hgrid_edge_y:standard_name = "latitude" ;
		SCHISM_hgrid_edge_y:units = "degrees_north" ;
		SCHISM_hgrid_edge_y:mesh = "SCHISM_hgrid" ;
		SCHISM_hgrid_edge_y:_Storage = "contiguous" ;
		SCHISM_hgrid_edge_y:_Endianness = "little" ;
	int64 edge_bottom_index(nSCHISM_hgrid_edge) ;
		edge_bottom_index:long_name = "bottom level index at each edge" ;
		edge_bottom_index:units = "non-dimensional" ;
		edge_bottom_index:mesh = "SCHISM_hgrid" ;
		edge_bottom_index:location = "edge" ;
		edge_bottom_index:start_index = 0LL ;
		edge_bottom_index:_Storage = "contiguous" ;
		edge_bottom_index:_Endianness = "little" ;

// global attributes:
		:Conventions = "CF-1.0, UGRID-1.0" ;
		:title = "SCHISM Model output" ;
		:source = "SCHISM model output version v10" ;
		:references = "http://ccrm.vims.edu/schismweb/" ;
		:history = "created by pyposeidon" ;
		:comment = "SCHISM Model output" ;
		:type = "SCHISM Model output" ;
		:VisIT_plugin = "https://schism.water.ca.gov/library/-/document_library/view/3476283" ;
		:_NCProperties = "version=2,netcdf=4.7.4,hdf5=1.10.6" ;
		:_SuperblockVersion = 0 ;
		:_IsNetcdf4 = 1 ;
		:_Format = "netCDF-4" ;
}
```

**Comment by pmav99** [comment]
TBH, I don't know what SCHISM is doing with this variable.

Since there are two values per node per timestamp, I guess that one of them is the `u` component and the other is `v` component.  Either that or one of them is the wind angle and the other the wind velocity. `u` and `v` seem more probable though since the name of the variable is wind_**speed**

In any case, thalassa at the moment does not know how to visualize this variable.

From what I can see, there is support for Vector Fields in Holoviews, but no idea if it works with unstructured meshes (the examples I see in the docs are with structured grids): https://holoviews.org/reference/elements/bokeh/VectorField.html
If it works, it should be possible to support it.

**Comment by josephzhang8** [comment]
'two' is used for dimensioning for variables like vectors or geometry. For vectors, u,v components are specified (not direction, mag.)

-Joseph

Y. Joseph Zhang
Web: schism.wiki
Office: 804 684 7466

**Comment by uturuncoglu** [comment]
@pmav99 There is an project at NCAR related to the processing and visualization of unstructured meshes. Maybe you could leverage from it. https://raijin.ucar.edu

**Comment by pmav99** [comment]
@uturuncoglu I assume that we can close this. If there is anything else, please open a new issue.
